dataset_image_url: 'http://vision.stanford.edu/aditya86/ImageNetDogs/images.tar'
dataset_annotation_url: 'http://vision.stanford.edu/aditya86/ImageNetDogs/annotation.tar'

dataset_path: 'resources/'
image_paths: 'resources/image_paths.txt'
